version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    hostname: influxdb
    ports:
<<<<<<< HEAD
    - "8083:8083"
    - "8086:8086"
=======
      - 8086:8086
>>>>>>> f97d051587feac6fa3504ab42fec3b3679d64f20
    volumes:
      - influxdb:/var/lib/influxdb
    restart:
      always
  kiana:
    build: .
    restart: always
    ports:
      - 3022:3022
    links:
      - influxdb
    depends_on:
      - redis
      - influxdb
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:1.6.7
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default
volumes:
  influxdb: